import os, sys
os.system ("import os, sys")
os.system ("%cd /content")
os.system ("from google.colab import drive")
os.system ("drive.mount('/content/drive')")
os.system ("from IPython.display import clear_output")
os.system ("from ipywidgets import Button")
os.system ("if not os.path.exists('/content/drive'):")
os.system ("print('Your drive is not mounted. Creating Fake Drive.')")
os.system ("os.makedirs('/content/drive/MyDrive')")
os.system ("!wget https://huggingface.co/Rejekts/project/resolve/main/project-main.zip -O '/content/project-main.zip' && unzip -n 'project-main.zip' -d /content/drive/MyDrive")
os.system ("!cd '/content/drive/MyDrive/project-main' && python download_files.py && pip install -r 'requirements-safe.txt'")
os.system ("!rm /content/project-main.zip")
os.system ("!rm -r /content/sample_data")
os.system ("!mkdir -p /content/dataset")
os.system ("clear_output()")
os.system ("Button(description='\u2714 Готово', button_style='success')")
